import { maior, media } from './ArrayVetor'
import { dobrar } from './map'
import { verficarIdade, par, reprovado, escolhaDia  } from './IfElse'
import { tabuada } from './For'
import { somar, multiplicar, dividir, subtrair, resto, potencia } from './Operacoes'